apiVersion: s3.services.k8s.aws/v1alpha1
kind: Bucket
metadata:
  name: bucket
spec:
  name: bucket-name
  acl: log-delivery-write
  logging:
    loggingEnabled:
      targetBucket: s3://hede-hude
      targetPrefix: "logging-"
  publicAccessBlock:
    blockPublicACLs: true
    blockPublicPolicy: true