apiVersion: eks.services.k8s.aws/v1alpha1
kind: Cluster
metadata:
  name: dev-cluster
spec:
  name: dev-cluster
  roleARN: dev-cluster
  resourcesVPCConfig:
    endpointPrivateAccess: true
    endpointPublicAccess: false
    subnetIDs:
      - "subnet-123"
      - "subnet-124"